### PR TITLE
lab: Fix coding style in demos and exercises

### LINKED ISSUE #82: Define and use coding style throughout demos and exercises
Currently there are coding style inconsistencies among source code files for demos and exercises.

I propose we define and use a simple coding style for C and assembly source code. I suggest we used [the Linux kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html). We could then use [checkpatch](https://www.kernel.org/doc/html/latest/dev-tools/checkpatch.html) to quickly validate compliance of C source code style.

### PR DESCRIPTION
**Pull request by dumitrache-adrian92**
Fixed coding style errors in a large amount of exercises without altering their functionality.
Changes include converting spaces to tabs, correct placement of parantheses for functions and instruction blocks, multiline comments etc.

Fixes #82
Signed-off-by: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
Most likely your local clone isn't in sync with the remote branch. This is why you have those extra files in `structuri-vectori-siruri/`.

Now that #138 is merged, you can use your `master` branch correctly to sync your current branch:

```
$ git checkout master

$ git remote add upstream https://github.com/systems-cs-pub-ro/iocla.git  # Add the official repo. If you have deployed your SSH key on GitHub (the intended way), use this link instead: git@github.com:systems-cs-pub-ro/iocla.git

$ git fetch upstream  # Get the information about the upstream branches locally.

$ git reset upstream master --hard  # Sync your master branch with its upstream correspondent. Always keep your master branch in sync with the remote and only make PRs from branches.

$ git checkout -  # Same as git checkout fix-coding-style

$ git rebase -i master  # This will change your current branch so that its commits lie "on top" of those from master. You mey get some conflicts here (probably not). If you do, don't be scared; it's good to learn to solve them. The earlier, the better.
```

**Comment by dumitrache-adrian92** [comment]
I've tried the above instructions, but I'm not sure how to go about fixing the above issues. Do I git pull now to sync previous changes?

**Comment by teodutu** [comment]
Do you still have those files? What does `git log` say? Paste the last 2 commits.

**Comment by dumitrache-adrian92** [comment]
Pasting last three because last two are identical
```
Author: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>
Date:   Wed Mar 8 10:33:44 2023 +0200

    lab: Fix coding style in demos and exercises
    
    Fixed coding style errors in a large amount of exercises without
    altering their functionality.
    Changes include converting spaces to tabs, correct placement of
    parantheses for functions and instruction blocks, multiline
:...skipping...
commit 25516f54dfeef04f034fa6dc71b5f26e6b0b72e8 (HEAD -> fix-coding-style)
Author: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>
Date:   Wed Mar 8 10:33:44 2023 +0200

    lab: Fix coding style in demos and exercises
    
    Fixed coding style errors in a large amount of exercises without
    altering their functionality.
    Changes include converting spaces to tabs, correct placement of
    parantheses for functions and instruction blocks, multiline
    comments etc.
    
    Fixes #82
    Signed-off-by: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>

commit bc3a7ddf7ad05d5deea7e2971ab48e001ba707ed (origin/master, origin/HEAD, master)
Author: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>
Date:   Wed Mar 8 10:53:00 2023 +0200

    Add headers
    
    Signed-off-by: Adrian-George Dumitrache <adriangeorge.d92@gmail.com>
```

**Comment by teodutu** [comment]
You haven't reset your master to the upstream. It is at this commit [1], but it should be at this one [2]. Did any of the commands I gave you fail?

[1] https://github.com/dumitrache-adrian92/iocla/commit/bc3a7ddf7ad05d5deea7e2971ab48e001ba707ed
[2] https://github.com/systems-cs-pub-ro/iocla/commit/91d56716bdecafe677e7e8bb3ad9400fdb8a1b74

**Comment by dumitrache-adrian92** [comment]
Yeah, my bad. git reset upstream master --hard failed
```
adrian@cave:~/Dropbox/uni/IOCLA/iocla$ git reset upstream master --hard
fatal: ambiguous argument 'upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by teodutu** [comment]
It seems you don't have a remote called `upstream`. What does `git remote -v` print?

**Comment by dumitrache-adrian92** [comment]
```
origin  git@github.com:dumitrache-adrian92/iocla.git (fetch)
origin  git@github.com:dumitrache-adrian92/iocla.git (push)
upstream        git@github.com:systems-cs-pub-ro/iocla.git (fetch)
upstream        git@github.com:systems-cs-pub-ro/iocla.git (push)
```

**Comment by teodutu** [comment]
Ok, now go to the `master` branch and run:

```
$ git fetch upstream

$ git reset upstream master --hard
```

Do these commands print any errors?

**Comment by dumitrache-adrian92** [comment]
Yeah
```
git reset upstream master --hard
fatal: ambiguous argument 'upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by darius-m** [comment]
Usually the `--` parameters should be placed before the other parameters. But in your case the issue is that `reset` only takes a single parameter as the refspec (the version you want to reset to - either a commit hash, branch name, tag, etc.). The refspec in your case should be `upstream/master`. Only some commands, like `pull` take the remote repository name as a separate parameter.

But you should usually avoid using hard resets as they will drop any changes / inconsistencies without warning you. Most of the time a `git pull --rebase upstream master` will do the trick just fine, unless you have added any changes to your master branch that conflict with the upstream. And in case there are any inconsistencies that you care about, you can correct them manually.

Please make sure to check the history using `git log` after performing a rebase, and confirm that the upstream master branch is behind or at the same point as your local branch. You may need to add the `--decorate` parameter set to one of `short`, `long` or `auto` to see the branch names in some cases.

**Note**: A good practice is to keep your master branch in sync with the remote, and then rebase your commits on top of it, like this:
```
git checkout master # go to your master branch
git pull --rebase upstream master # fetch the changes from the upstream repo; use `rebase` as the conflict resolving strategy
git log # check that the pull completed successfully
git push origin mater # update your fork's master
git checkout <your-branch> # go to the branch with your changes
git rebase master # apply your commits on top of the master branch - this should keep your commits on top of the newly updated master branch
git log -p  # check the state of your branch to see if all commits applied correctly (also prints the diffs so you can double check)
git push origin <your-branch> # this will not work if the branch was previously pushed on your fork, and you will need to add `-f` to force update it - when solving conflicts this is unavoidable
```

This flow is more complex, but will decrease the likelihood of having any unexpected conflicts with the remote branches and losing changes.

**Comment by dumitrache-adrian92** [comment]
Welp, I think I've created another problem now, I'm not breaking other PRs, but modifying one of my own for some reason.

**Comment by darius-m** [comment]
What do you mean by "modifying one of your own?"

**Comment by dumitrache-adrian92** [comment]
Not modifying actually, sorry, instead I seem to have added a commit to this PR which has already been merged in [#138](https://github.com/systems-cs-pub-ro/iocla/pull/138). If it helps, I chose "accept current change" or something of the sort  when running:
```
git pull --rebase upstream master
```

Sorry for the mess.

**Review by teodutu — APPROVED** [review]
Looks great! Sorry for taking so long to approve this. I forgot about it :(.

**Comment by teodutu** [comment]
And thanks @darius-m for the git-related help.

**Pull request merged**
